name: Delete workflow run record
on:
# Run weekly, at 00:00 on sunday.
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: 删除当前仓库的历史工作流记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3
