name: wechat-sport-robot

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '35 15 * * *'
  pull_request:
    branches: [ main ]

jobs:
  robot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 添加了 token，因为 checkout 需要权限
          repository: "https://github.com/FlameTech6/WeChat_Sport_Robot.git"  # 将YOUR_REPOSITORY替换为您实际的仓库地址
          ref: main  # 将main替换为您实际的分支

      - name: Set up Python 3.9 with architecture x64
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "ACCOUNT=${{ secrets.ACCOUNT }} >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }} >> $GITHUB_ENV"

      - name: Run the robot
        run: |
          python3 ./main.py
