name: wechat-sport-robot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
      - run: pip install requests==2.26.0
      - run: python main.py
