name: wechat-sport-robot

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '35 15 * * *'
  pull_request:
    branches: [ main ]

jobs:
  robot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 添加了 token，因为 checkout 需要权限

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the robot
        run: |
          python3 ./main.py

      - name: Set environment variables
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
