name: wechat-sport-robot

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '35 15 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'
      - run: pip install requests,time,re
      - run: python ./main.py
      - run: echo "ACCOUNT=${{ secrets.ACCOUNT }} >> $GITHUB_ENV
      - run: echo "PASSWORD=${{ secrets.PASSWORD }} >> $GITHUB_ENV"
